config/routes.rb
PFF::Application.routes.draw do
  match 'orders/payment'
  match 'orders/request_payment_status'

  resources :transactions

  resources :transaction_types

  resources :order_details

  resources :orders

  resources :order_statuses

  resources :order_logs

  resources :payment_methods

  resources :payment_types

  resources :quotations

  resources :accounts

  resources :products

  resources :points

  resources :currencies

  resources :categories

  resources :countries

  resources :profiles

  devise_for :users

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :id, :point_id #, credit_card_number
  has_one :transaction

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
	belongs_to :product
	#validate, only 1 product in cart
  validates_uniqueness_of  :user_id, :scope => [ :product_id]
  validates_numericality_of :quantity, :only_integer => true, :greater_than => 0

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategory, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category"
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_one :point
	has_one :product, :through =>:point 
	has_one :quotation

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, :dependent => :destroy
  belongs_to :order_status
  has_many :order_logs
  belongs_to :payment_method
  belongs_to :payment_type, :primary_key => :code
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :point
end

app/models/order_log.rb
class OrderLog < ActiveRecord::Base
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_one :order
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_many :orders
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_one :order
end

app/models/point.rb
class Point < ActiveRecord::Base
	belongs_to :currency
	has_one :product
  has_one :order_detail
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :point
	has_many :category
	has_many :cart
  has_one :order_detail
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_one :user
=begin
  #valida null
	validates_presence_of  :first_name,
		:last_name,
		:sex_id,
		:date_of_birth,
		:CPF,
		:RG,
		:street_address1,
		:street_number,
		:city,
		:zip_code,
		:state_id,
		:country_id,
		:phone_country_id,
		:phone_number,
    :message => "não pode ficar em branco."

    #valida unico
    validates_uniqueness_of :CPF, :RG,
    :on => :create,
    :allow_blank => true,
    :message => "já cadastrado em nossa base."

    #valida numericos
    validates_numericality_of :CPF,
    	:RG,
    	:zip_code,
    	:street_number,
    	:phone_number,
    	:phone_country_id,
    :only_integer => true,
    :allow_blank => true,
    :message => "deve ser digitado somente números."
=end
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	belongs_to :currency
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :transaction_type, :primary_key => :code, :foreign_key => :transaction_type_code
  belongs_to :account, :primary_key => :id, :foreign_key => :account_from_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :profile
  has_many :carts
  has_many :orders
  has_one :account
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.xml
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.xml
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.xml
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.xml
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to(@currency, :notice => 'Currency was successfully created.') }
        format.xml  { render :xml => @currency, :status => :created, :location => @currency }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @currency.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.xml
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to(@currency, :notice => 'Currency was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @currency.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.xml
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to(currencies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Symbol</th>
    <th>Abbreviation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.name %></td>
    <td><%= currency.symbol %></td>
    <td><%= currency.abbreviation %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>

<p>
  <b>Symbol:</b>
  <%= @currency.symbol %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @currency.abbreviation %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>