config/routes.rb
PFF::Application.routes.draw do
  match 'orders/payment'
  match 'orders/request_payment_status'

  resources :transactions

  resources :transaction_types

  resources :order_details

  resources :orders

  resources :order_statuses

  resources :order_logs

  resources :payment_methods

  resources :payment_types

  resources :quotations

  resources :accounts

  resources :products

  resources :points

  resources :currencies

  resources :categories

  resources :countries

  resources :profiles

  devise_for :users

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :id, :point_id #, credit_card_number
  has_one :transaction

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
	belongs_to :product
	#validate, only 1 product in cart
  validates_uniqueness_of  :user_id, :scope => [ :product_id]
  validates_numericality_of :quantity, :only_integer => true, :greater_than => 0

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategory, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category"
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_one :point
	has_one :product, :through =>:point 
	has_one :quotation

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, :dependent => :destroy
  belongs_to :order_status
  has_many :order_logs
  belongs_to :payment_method
  belongs_to :payment_type, :primary_key => :code
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :point
end

app/models/order_log.rb
class OrderLog < ActiveRecord::Base
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_one :order
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_many :orders
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_one :order
end

app/models/point.rb
class Point < ActiveRecord::Base
	belongs_to :currency
	has_one :product
  has_one :order_detail
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :point
	has_many :category
	has_many :cart
  has_one :order_detail
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_one :user
=begin
  #valida null
	validates_presence_of  :first_name,
		:last_name,
		:sex_id,
		:date_of_birth,
		:CPF,
		:RG,
		:street_address1,
		:street_number,
		:city,
		:zip_code,
		:state_id,
		:country_id,
		:phone_country_id,
		:phone_number,
    :message => "não pode ficar em branco."

    #valida unico
    validates_uniqueness_of :CPF, :RG,
    :on => :create,
    :allow_blank => true,
    :message => "já cadastrado em nossa base."

    #valida numericos
    validates_numericality_of :CPF,
    	:RG,
    	:zip_code,
    	:street_number,
    	:phone_number,
    	:phone_country_id,
    :only_integer => true,
    :allow_blank => true,
    :message => "deve ser digitado somente números."
=end
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	belongs_to :currency
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :transaction_type, :primary_key => :code, :foreign_key => :transaction_type_code
  belongs_to :account, :primary_key => :id, :foreign_key => :account_from_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :profile
  has_many :carts
  has_many :orders
  has_one :account
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  # GET /quotations
  # GET /quotations.xml
  def index
    @quotations = Quotation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quotations }
    end
  end

  # GET /quotations/1
  # GET /quotations/1.xml
  def show
    @quotation = Quotation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quotation }
    end
  end

  # GET /quotations/new
  # GET /quotations/new.xml
  def new
    @quotation = Quotation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quotation }
    end
  end

  # GET /quotations/1/edit
  def edit
    @quotation = Quotation.find(params[:id])
  end

  # POST /quotations
  # POST /quotations.xml
  def create
    @quotation = Quotation.new(params[:quotation])

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to(@quotation, :notice => 'Quotation was successfully created.') }
        format.xml  { render :xml => @quotation, :status => :created, :location => @quotation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quotation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quotations/1
  # PUT /quotations/1.xml
  def update
    @quotation = Quotation.find(params[:id])

    respond_to do |format|
      if @quotation.update_attributes(params[:quotation])
        format.html { redirect_to(@quotation, :notice => 'Quotation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quotation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.xml
  def destroy
    @quotation = Quotation.find(params[:id])
    @quotation.destroy

    respond_to do |format|
      format.html { redirect_to(quotations_url) }
      format.xml  { head :ok }
    end
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.erb
<%= form_for(@quotation) do |f| %>
  <% if @quotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

      <ul>
      <% @quotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :currency_id %><br />
		<%= collection_select :quotation, :currency_id, Currency.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotations/edit.html.erb
<h1>Editing quotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @quotation %> |
<%= link_to 'Back', quotations_path %>

app/views/quotations/index.html.erb
<h1>Listing quotations</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Currency</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotations.each do |quotation| %>
  <tr>
    <td><%= quotation.date %></td>
    <td><%= quotation.currency_id %></td>
    <td><%= quotation.value %></td>
    <td><%= link_to 'Show', quotation %></td>
    <td><%= link_to 'Edit', edit_quotation_path(quotation) %></td>
    <td><%= link_to 'Destroy', quotation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quotation', new_quotation_path %>

app/views/quotations/new.html.erb
<h1>New quotation</h1>

<%= render 'form' %>

<%= link_to 'Back', quotations_path %>

app/views/quotations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @quotation.date %>
</p>

<p>
  <b>Currency:</b>
  <%= @quotation.currency_id %>
</p>

<p>
  <b>Value:</b>
  <%= @quotation.value %>
</p>


<%= link_to 'Edit', edit_quotation_path(@quotation) %> |
<%= link_to 'Back', quotations_path %>