config/routes.rb
PFF::Application.routes.draw do
  match 'orders/payment'
  match 'orders/request_payment_status'

  resources :transactions

  resources :transaction_types

  resources :order_details

  resources :orders

  resources :order_statuses

  resources :order_logs

  resources :payment_methods

  resources :payment_types

  resources :quotations

  resources :accounts

  resources :products

  resources :points

  resources :currencies

  resources :categories

  resources :countries

  resources :profiles

  devise_for :users

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :id, :point_id #, credit_card_number
  has_one :transaction

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
	belongs_to :product
	#validate, only 1 product in cart
  validates_uniqueness_of  :user_id, :scope => [ :product_id]
  validates_numericality_of :quantity, :only_integer => true, :greater_than => 0

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategory, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category"
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_one :point
	has_one :product, :through =>:point 
	has_one :quotation

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_details, :dependent => :destroy
  belongs_to :order_status
  has_many :order_logs
  belongs_to :payment_method
  belongs_to :payment_type, :primary_key => :code
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :point
end

app/models/order_log.rb
class OrderLog < ActiveRecord::Base
  belongs_to :order
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_one :order
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  has_many :orders
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  has_one :order
end

app/models/point.rb
class Point < ActiveRecord::Base
	belongs_to :currency
	has_one :product
  has_one :order_detail
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :point
	has_many :category
	has_many :cart
  has_one :order_detail
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_one :user
=begin
  #valida null
	validates_presence_of  :first_name,
		:last_name,
		:sex_id,
		:date_of_birth,
		:CPF,
		:RG,
		:street_address1,
		:street_number,
		:city,
		:zip_code,
		:state_id,
		:country_id,
		:phone_country_id,
		:phone_number,
    :message => "não pode ficar em branco."

    #valida unico
    validates_uniqueness_of :CPF, :RG,
    :on => :create,
    :allow_blank => true,
    :message => "já cadastrado em nossa base."

    #valida numericos
    validates_numericality_of :CPF,
    	:RG,
    	:zip_code,
    	:street_number,
    	:phone_number,
    	:phone_country_id,
    :only_integer => true,
    :allow_blank => true,
    :message => "deve ser digitado somente números."
=end
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	belongs_to :currency
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :transaction_type, :primary_key => :code, :foreign_key => :transaction_type_code
  belongs_to :account, :primary_key => :id, :foreign_key => :account_from_id
end

app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
    has_one :transaction
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :profile
  has_many :carts
  has_many :orders
  has_one :account
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.text_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_type_code %><br />
    <%= f.text_field :transaction_type_code %>
  </div>
  <div class="field">
    <%= f.label :points_value %><br />
    <%= f.text_field :points_value %>
  </div>
  <div class="field">
    <%= f.label :account_from_id %><br />
    <%= f.text_field :account_from_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Account</th>
    <th>Transaction type code</th>
    <th>Points value</th>
    <th>Account from</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.date %></td>
    <td><%= transaction.account_id %></td>
    <td><%= transaction.transaction_type_code %></td>
    <td><%= transaction.points_value %></td>
    <td><%= transaction.account_from_id %></td>
    <td><%= link_to 'Show', transaction %></td>
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @transaction.date %>
</p>

<p>
  <b>Account:</b>
  <%= @transaction.account_id %>
</p>

<p>
  <b>Transaction type code:</b>
  <%= @transaction.transaction_type.name %>
</p>

<p>
  <b>Points value:</b>
  <%= @transaction.points_value %>
</p>

<p>
  <b>Account from:</b>
  <%= @transaction.account.user.profile.first_name  + " - " +@transaction.account.user.email %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>